"""Curated ingredient corpus: canonical names, merges, FooDB aliases, French translations.

The corpus was validated against three sources:
- RecipeNLG mirror (~500k recipes) for co-occurrence signal
- FoodAtlas v4.8 (Apache-2.0) for entity validation
- FooDB 2020-04-07 (open) for measured molecular profiles + flavor descriptors
"""

# Preparation modifiers stripped during canonicalization of recipe ingredient strings
PREP_MODIFIERS = {
    "fresh", "frozen", "dried", "ground", "chopped", "canned", "cold", "hot",
    "boiling", "instant", "cooked", "raw", "whole", "sliced", "diced", "grated",
    "shredded", "powdered", "crushed", "minced", "melted", "softened", "warm",
    "boneless", "skinless", "lean", "large", "small", "medium", "ripe", "baby",
    "prepared", "packed", "granulated", "sifted", "beaten", "unsalted", "salted",
    "freshly", "leftover", "quick", "cooking", "liquid", "thawed", "peeled",
    "unpeeled", "seedless", "pitted", "regular", "plain", "pure", "extra",
    "very", "fine", "finely", "coarse", "coarsely", "thin", "thinly", "thick",
    "lightly", "light", "dark", "mild", "sharp", "sweetened", "unsweetened",
}

SINGULAR_EXCEPTIONS = {"asparagus", "hummus", "couscous", "molasses", "swiss", "citrus", "brussels"}


def canonical(ing: str) -> str:
    """Normalize a raw recipe ingredient string to its canonical form."""
    words = [w for w in ing.split() if w not in PREP_MODIFIERS]
    c = " ".join(words) if words else ing
    parts = c.split()
    last = parts[-1] if parts else c
    if last in SINGULAR_EXCEPTIONS:
        return c
    if c.endswith("ies"):
        c = c[:-3] + "y"
    elif c.endswith(("oes", "shes", "ches", "xes")):
        c = c[:-2]
    elif c.endswith("s") and not c.endswith("ss") and not c.endswith("us"):
        c = c[:-1]
    return c


# Variant -> final ingredient (applied after canonical())
MERGES = {
    # produce variants
    "white onion": "onion", "yellow onion": "onion", "sweet onion": "onion",
    "vidalia onion": "onion", "spanish onion": "onion", "bermuda onion": "onion",
    "pearl onion": "onion", "purple onion": "red onion",
    "green tomato": "tomato", "cherry tomato": "tomato", "italian plum tomato": "tomato",
    "italian tomato": "tomato", "red tomato": "tomato", "italian stewed tomato": "tomato",
    "ro-tel tomato": "tomato", "roma tomato": "tomato", "plum tomato": "tomato",
    "white potato": "potato", "red potato": "potato", "baking potato": "potato",
    "new potato": "potato", "irish potato": "potato", "all-purpose potato": "potato",
    "new red potato": "potato", "red new potato": "potato", "brown potato": "potato",
    "mashed potato": "potato", "mashed sweet potato": "sweet potato",
    "green pepper": "green bell pepper", "sweet green pepper": "green bell pepper",
    "green sweet pepper": "green bell pepper", "sweet pepper": "bell pepper",
    "red pepper": "red bell pepper", "sweet red pepper": "red bell pepper",
    "red sweet pepper": "red bell pepper", "yellow pepper": "yellow bell pepper",
    "jalapeno": "jalapeno pepper", "green chile pepper": "jalapeno pepper",
    "green chili pepper": "jalapeno pepper", "green chile": "jalapeno pepper",
    "green chili": "jalapeno pepper", "cayenne": "cayenne pepper",
    "red cayenne pepper": "cayenne pepper", "cayenne red pepper": "cayenne pepper",
    "broccoli floret": "broccoli", "head broccoli": "broccoli", "stalks broccoli": "broccoli",
    "bunches broccoli": "broccoli", "cauliflower floret": "cauliflower",
    "head cauliflower": "cauliflower", "head cabbage": "cabbage",
    "green cabbage": "cabbage", "head green cabbage": "cabbage", "head of cabbage": "cabbage",
    "head red cabbage": "red cabbage", "chinese vegetable": "chinese cabbage",
    "button mushroom": "mushroom", "white mushroom": "mushroom",
    "romaine": "lettuce", "romaine lettuce": "lettuce", "head romaine": "lettuce",
    "head romaine lettuce": "lettuce", "iceberg lettuce": "lettuce",
    "head iceberg lettuce": "lettuce", "boston lettuce": "lettuce",
    "bibb lettuce": "lettuce", "leaf lettuce": "lettuce", "torn lettuce": "lettuce",
    "heads lettuce": "lettuce", "celery stalk": "celery", "stalk celery": "celery",
    "stalks celery": "celery", "torn spinach": "spinach",
    "green asparagus": "asparagus", "cans asparagus": "asparagus",
    "string bean": "green bean", "wax bean": "green bean", "yellow wax bean": "green bean",
    "yellow bean": "green bean", "green lima bean": "lima bean", "butter bean": "lima bean",
    "garbanzo bean": "chickpea", "garbanzo": "chickpea",
    "dark red kidney bean": "kidney bean", "red kidney bean": "kidney bean",
    "light red kidney bean": "kidney bean", "red kidney": "kidney bean",
    "kidney": "kidney bean", "white kidney bean": "cannellini bean",
    "white bean": "navy bean", "dry navy bean": "navy bean",
    "northern bean": "great northern bean", "cans great northern bean": "great northern bean",
    "english pea": "pea", "lesueur pea": "pea", "tiny pea": "pea", "garden pea": "pea",
    "green split pea": "pea", "sweet pea": "pea", "pea pod": "snow pea",
    "black-eyed pea": "black-eyed pea", "dry lentil": "lentil",
    "sweet corn": "corn", "yellow corn": "corn", "white corn": "corn",
    "kernel corn": "corn", "peg corn": "corn", "niblets corn": "corn",
    "shoepeg corn": "corn", "white shoepeg corn": "corn", "white shoe peg corn": "corn",
    "cream-style corn": "corn", "peg white corn": "corn",
    "acorn": "acorn squash", "yellow squash": "zucchini",
    "grape": "grape", "red grape": "grape", "white grape": "grape",
    "green grape": "grape", "seedless grape": "grape", "red seedless grape": "grape",
    "white seedless grape": "grape", "green seedless grape": "grape",
    # fruits
    "tart apple": "apple", "red apple": "apple", "green apple": "apple",
    "baking apple": "apple", "delicious apple": "apple", "red delicious apple": "apple",
    "golden delicious apple": "apple", "pared apple": "apple",
    "red cherry": "cherry", "black cherry": "cherry", "sweet cherry": "cherry",
    "sour cherry": "cherry", "dark sweet cherry": "cherry", "tart cherry": "cherry",
    "bing cherry": "cherry", "white cherry": "cherry", "green cherry": "cherry",
    "red raspberry": "raspberry", "red currant": "currant",
    "golden raisin": "raisin", "dark raisin": "raisin", "yellow raisin": "raisin",
    "light raisin": "raisin", "white raisin": "raisin", "mashed banana": "banana",
    "mashed strawberry": "strawberry", "mashed fig": "fig", "mandarin": "mandarin orange",
    "melon": "honeydew melon", "coconut milk": "coconut",
    # herbs & spices
    "sweet basil": "basil", "leaf basil": "basil", "italian parsley": "parsley",
    "leaf oregano": "oregano", "dill weed": "dill", "peppermint": "mint",
    "cilantro": "coriander leaf", "coriander": "coriander seed",
    "caraway seed": "caraway", "cardamon": "cardamom", "anise seed": "anise",
    "cinnamon stick": "cinnamon", "red cinnamon": "cinnamon",
    "vanilla bean": "vanilla", "black peppercorn": "black pepper",
    "peppercorn": "black pepper", "cracked pepper": "black pepper",
    "cracked black pepper": "black pepper", "coarse black pepper": "black pepper",
    "coarse pepper": "black pepper", "garlic pepper": "black pepper",
    "clove garlic": "garlic", "clove of garlic": "garlic", "garlic clove": "garlic",
    "buds garlic": "garlic", "garlic powder": "garlic", "ginger root": "ginger",
    "spring onion": "green onion", "scallion": "green onion",
    # meats & fish
    "ground beef": "beef", "hamburger": "beef", "hamburger meat": "beef",
    "round steak": "beef", "flank steak": "beef", "chuck steak": "beef",
    "beef tenderloin": "beef", "stewing beef": "beef", "cubed beef": "beef",
    "round beef": "beef", "beef chuck roast": "beef", "extra beef": "beef",
    "stew meat": "beef", "corned beef": "beef", "barbecue beef": "beef",
    "chicken breast": "chicken", "chicken thigh": "chicken", "chicken leg": "chicken",
    "white chicken": "chicken", "boned chicken": "chicken", "fryer chicken": "chicken",
    "stewing chicken": "chicken", "broiler-fryer chicken": "chicken",
    "chicken meat": "chicken", "ground turkey": "turkey", "turkey breast": "turkey",
    "pork tenderloin": "pork", "pork loin": "pork", "pork chop": "pork",
    "pork shoulder": "pork", "barbecue pork": "pork", "boiled ham": "ham",
    "deli ham": "ham", "shaved ham": "ham", "ham steak": "ham",
    "fully ham": "ham", "thin slices ham": "ham",
    "crisp bacon": "bacon", "crisply bacon": "bacon", "crisp fried bacon": "bacon",
    "turkey bacon": "bacon", "bacon dripping": "bacon",
    "pork sausage": "sausage", "italian sausage": "sausage", "bulk sausage": "sausage",
    "sweet italian sausage": "sausage", "sweet sausage": "sausage",
    "turkey sausage": "sausage", "kielbasa sausage": "sausage", "loose sausage": "sausage",
    "hard salami": "salami", "crabmeat": "crab", "crab meat": "crab",
    "lump crab meat": "crab", "white crab meat": "crab", "imitation crab": "crab",
    "tuna fish": "tuna", "white tuna": "tuna", "pink salmon": "salmon",
    "red salmon": "salmon", "cod fillet": "cod", "catfish fillet": "catfish",
    "peeled shrimp": "shrimp", "jumbo shrimp": "shrimp", "tiny shrimp": "shrimp",
    "salad shrimp": "shrimp", "bay scallop": "scallop", "deer": "venison",
    # dairy
    "parmesan": "parmesan cheese", "freshly parmesan": "parmesan cheese",
    "freshly parmesan cheese": "parmesan cheese", "romano": "romano cheese",
    "monterey jack": "jack cheese", "monterey jack cheese": "jack cheese",
    "philadelphia cream cheese": "cream cheese", "sharp cheddar cheese": "cheddar cheese",
    "low-fat mozzarella cheese": "mozzarella cheese", "roquefort cheese": "blue cheese",
    "low-fat cottage cheese": "cottage cheese", "cream-style cottage cheese": "cottage cheese",
    "low-fat ricotta cheese": "ricotta cheese", "nonfat yogurt": "yogurt",
    "plain yogurt": "yogurt", "nonfat plain yogurt": "yogurt", "low-fat yogurt": "yogurt",
    "low-fat plain yogurt": "yogurt", "vanilla yogurt": "yogurt",
    "lemon yogurt": "yogurt", "strawberry yogurt": "yogurt",
    "whipping cream": "heavy cream", "provolone": "provolone cheese",
    # pantry with real profiles
    "white vinegar": "vinegar", "cider vinegar": "vinegar",
    "apple cider vinegar": "vinegar", "tarragon vinegar": "vinegar",
    "rice vinegar": "vinegar", "raspberry vinegar": "vinegar", "red vinegar": "vinegar",
    "apple vinegar": "vinegar", "salad vinegar": "vinegar", "dark vinegar": "vinegar",
    "dry mustard": "mustard", "yellow mustard": "mustard", "dijon mustard": "mustard",
    "brown mustard": "mustard", "spicy mustard": "mustard", "honey mustard": "mustard",
    "regular mustard": "mustard", "horseradish mustard": "mustard",
    "white horseradish": "horseradish", "tomato ketchup": "ketchup",
    "catsup": "ketchup", "bottles ketchup": "ketchup",
    "dark molasses": "molasses", "light molasses": "molasses",
    "sorghum molasses": "molasses", "grandma's molasses": "molasses",
    "rabbit molasses": "molasses", "dry sherry": "sherry",
    "dry white wine": "white wine", "dry red wine": "red wine",
    "dark rum": "rum", "light rum": "rum", "green olive": "olive",
    "black pitted olive": "black olive", "stuffed olive": "olive",
    "spanish olive": "olive", "salad olive": "olive",
    "smooth peanut butter": "peanut butter", "chunky peanut butter": "peanut butter",
    "crunchy peanut butter": "peanut butter", "extra crunchy peanut butter": "peanut butter",
    "jif peanut butter": "peanut butter", "cider": "apple cider",
    "black coffee": "coffee", "long grain rice": "rice", "minute rice": "rice",
    "long grain white rice": "rice", "regular long grain rice": "rice",
    "long-grain rice": "rice", "yellow rice": "rice", "spanish rice": "rice",
    "uncle ben's rice": "rice", "white rice": "rice", "long grain wild rice": "wild rice",
    "corn meal": "cornmeal", "yellow cornmeal": "cornmeal",
    "rolled oat": "oat", "old-fashioned oat": "oat", "quick-cooking oat": "oat",
    "cook oat": "oat", "regular oat": "oat", "oatmeal": "oat",
    "pearl barley": "barley", "cracked wheat": "bulgur", "bulgur wheat": "bulgur",
    "cocoa powder": "cocoa", "baking cocoa": "cocoa", "unsweetened cocoa": "cocoa",
    "baking chocolate": "chocolate", "unsweetened chocolate": "chocolate",
    "semi-sweet chocolate": "chocolate", "bittersweet chocolate": "chocolate",
    "white chocolate": "chocolate", "dipping chocolate": "chocolate",
    "extra virgin olive oil": "olive oil", "virgin olive oil": "olive oil",
    "cashew nut": "cashew", "pistachio nut": "pistachio", "black walnut": "walnut",
    "california walnut": "walnut", "slivered almond": "almond",
    "blanched almond": "almond", "blanched slivered almond": "almond",
    "slivered blanched almond": "almond", "spanish peanut": "peanut",
    "hickory nut": "pecan", "orange zest": "orange peel", "lemon zest": "lemon peel",
    "dill pickle": "pickle", "sweet pickle": "pickle", "pickling cucumber": "cucumber",
    "red beet": "beet", "swiss chard": "chard", "collard": "collard green",
    "egg substitute": "egg white", "firm tofu": "tofu",
    "curry": "curry powder", "chili powder": "chili powder",
}

# Final ingredient -> FooDB food name (exact matching on Food.csv names/scientific names)
FOODB_ALIASES = {
    # meats
    "bacon": "domestic pig", "ham": "domestic pig", "pork": "domestic pig",
    "sausage": "domestic pig", "salami": "domestic pig", "chorizo": "domestic pig",
    "lard": "domestic pig", "lamb": "sheep (mutton, lamb)",
    "veal": "cattle (beef, veal)", "beef": "cattle (beef, veal)",
    "venison": "deer", "turkey": "turkey", "quail": "common quail",
    # fish & seafood
    "tuna": "skipjack tuna", "cod": "atlantic cod", "salmon": "atlantic salmon",
    "haddock": "haddock", "red snapper": "snapper", "orange roughy": "orange roughy",
    "catfish": "channel catfish", "anchovy": "anchovy", "shrimp": "crustaceans",
    "crab": "crustaceans", "mussel": "blue mussel", "clam": "clam",
    "oyster": "eastern oyster", "scallop": "scallop",
    # vegetables
    "artichoke": "globe artichoke", "green onion": "welsh onion",
    "onion": "garden onion", "red onion": "red onion", "celery": "celery stalks",
    "beet": "common beet", "zucchini": "green zucchini", "rhubarb": "garden rhubarb",
    "mushroom": "common mushroom", "pumpkin": "cucurbita",
    "pumpkin seed": "cucurbita", "acorn squash": "winter squash",
    "butternut squash": "butternut squash", "squash": "winter squash",
    "collard green": "kale", "chinese cabbage": "chinese cabbage",
    "chard": "swiss chard", "sweet potato": "sweet potato",
    "pickle": "cucumber", "sauerkraut": "cabbage", "romaine": "lettuce",
    "lettuce": "lettuce", "pea": "common pea", "green pea": "common pea",
    "snow pea": "common pea",
    # peppers
    "bell pepper": "green bell pepper", "green bell pepper": "green bell pepper",
    "red bell pepper": "red bell pepper", "yellow bell pepper": "yellow bell pepper",
    "jalapeno pepper": "pepper", "cayenne pepper": "pepper",
    "chili pepper": "pepper", "banana pepper": "pepper",
    "paprika": "pepper", "pimento": "pepper",
    "chili powder": "pepper", "black pepper": "pepper (spice)",
    "white pepper": "pepper (spice)",
    # fruits
    "blueberry": "highbush blueberry", "cranberry": "american cranberry",
    "currant": "redcurrant", "raspberry": "red raspberry", "cherry": "sweet cherry",
    "prune": "european plum", "orange": "sweet orange", "orange peel": "sweet orange",
    "lemon peel": "lemon", "mandarin orange": "mandarin orange (clementine, tangerine)",
    "honeydew melon": "muskmelon", "cantaloupe": "muskmelon", "kiwi": "kiwi",
    "raisin": "common grape", "grape": "common grape", "apple cider": "apple",
    # herbs & spices
    "basil": "sweet basil", "bay leaf": "sweet bay", "oregano": "common oregano",
    "thyme": "common thyme", "sage": "common sage", "marjoram": "sweet marjoram",
    "mint": "peppermint", "coriander leaf": "coriander", "coriander seed": "coriander",
    "fennel seed": "fennel", "vanilla": "vanilla",
    # nuts & seeds
    "cashew": "cashew nut", "pecan": "pecan nut", "peanut butter": "peanut",
    "sesame oil": "sesame", "sesame seed": "sesame", "sunflower seed": "sunflower",
    "peanut oil": "peanut", "flaxseed": "flaxseed",
    # legumes
    "black bean": "black bean", "pinto bean": "pinto bean", "navy bean": "navy bean",
    "kidney bean": "kidney bean", "cannellini bean": "kidney bean",
    "great northern bean": "kidney bean", "lima bean": "lima bean",
    "red bean": "adzuki bean", "green bean": "green bean", "chickpea": "chickpea",
    "black-eyed pea": "cowpea", "tofu": "soybean",
    # dairy & eggs
    "egg white": "eggs", "egg yolk": "eggs", "heavy cream": "cream",
    "sour cream": "sour cream", "yogurt": "yogurt", "cream cheese": "cream cheese",
    "cottage cheese": "cottage cheese", "cheddar cheese": "cheddar cheese",
    "swiss cheese": "swiss cheese", "mozzarella cheese": "mozzarella cheese",
    "parmesan cheese": "parmesan cheese", "romano cheese": "romano cheese",
    "provolone cheese": "provolone cheese", "ricotta cheese": "ricotta cheese",
    "feta cheese": "feta cheese", "blue cheese": "cheese",
    "goat cheese": "goat cheese", "gouda cheese": "gouda cheese",
    "muenster cheese": "muenster cheese", "gruyere cheese": "gruyere cheese",
    "jack cheese": "monterey cheese", "neufchatel cheese": "neufchatel cheese",
    # pantry
    "cocoa": "cocoa bean", "chocolate": "cocoa bean", "tomato": "garden tomato",
    "cornmeal": "corn", "popcorn": "corn", "vinegar": "common vinegar",
    "balsamic vinegar": "common vinegar", "ketchup": "ketchup",
    "mustard": "mustard", "molasses": "molasses", "honey": "honey",
    "olive oil": "olive", "olive": "olive", "black olive": "olive",
    "canola oil": "canola", "safflower oil": "safflower",
    "wild rice": "wild rice", "brown rice": "rice", "couscous": "wheat",
    "bulgur": "wheat", "sorghum": "sorghum", "tapioca": "cassava",
    "arrowroot": "arrowhead", "water chestnut": "water chestnut",
    "bamboo shoot": "bamboo shoots", "curry powder": "curry powder",
    # drinks
    "beer": "beer", "rum": "rum", "vodka": "vodka", "sherry": "sherry",
    "sake": "sake", "red wine": "red wine", "white wine": "white wine",
    "tea": "tea", "coffee": "coffee",
}

# English -> French, with category for UI grouping
# Categories: fruit, legume(=vegetable), herbe, epice, viande, poisson, fromage,
#             laitier, feculent, noix, condiment, boisson, autre
INGREDIENTS = {
    "acorn squash": ("courge poivrée", "legume"),
    "allspice": ("piment de la Jamaïque", "epice"),
    "almond": ("amande", "noix"),
    "anchovy": ("anchois", "poisson"),
    "anise": ("anis", "epice"),
    "apple": ("pomme", "fruit"),
    "apple cider": ("cidre", "boisson"),
    "apricot": ("abricot", "fruit"),
    "arrowroot": ("arrow-root", "feculent"),
    "artichoke": ("artichaut", "legume"),
    "asparagus": ("asperge", "legume"),
    "avocado": ("avocat", "legume"),
    "bacon": ("bacon", "viande"),
    "balsamic vinegar": ("vinaigre balsamique", "condiment"),
    "bamboo shoot": ("pousse de bambou", "legume"),
    "banana": ("banane", "fruit"),
    "banana pepper": ("piment banane", "legume"),
    "barley": ("orge", "feculent"),
    "basil": ("basilic", "herbe"),
    "bay leaf": ("laurier", "herbe"),
    "beef": ("bœuf", "viande"),
    "beer": ("bière", "boisson"),
    "beet": ("betterave", "legume"),
    "bell pepper": ("poivron", "legume"),
    "black bean": ("haricot noir", "legume"),
    "black olive": ("olive noire", "condiment"),
    "black pepper": ("poivre noir", "epice"),
    "black-eyed pea": ("haricot cornille", "legume"),
    "blackberry": ("mûre", "fruit"),
    "blue cheese": ("fromage bleu", "fromage"),
    "blueberry": ("myrtille", "fruit"),
    "broccoli": ("brocoli", "legume"),
    "brown rice": ("riz complet", "feculent"),
    "bulgur": ("boulgour", "feculent"),
    "butternut squash": ("courge butternut", "legume"),
    "cabbage": ("chou", "legume"),
    "cannellini bean": ("haricot cannellini", "legume"),
    "canola oil": ("huile de colza", "condiment"),
    "cantaloupe": ("melon cantaloup", "fruit"),
    "caper": ("câpre", "condiment"),
    "caraway": ("carvi", "epice"),
    "cardamom": ("cardamome", "epice"),
    "carrot": ("carotte", "legume"),
    "cashew": ("noix de cajou", "noix"),
    "catfish": ("poisson-chat", "poisson"),
    "cauliflower": ("chou-fleur", "legume"),
    "cayenne pepper": ("piment de Cayenne", "epice"),
    "celery": ("céleri", "legume"),
    "chard": ("blette", "legume"),
    "cheddar cheese": ("cheddar", "fromage"),
    "cherry": ("cerise", "fruit"),
    "chervil": ("cerfeuil", "herbe"),
    "chestnut": ("châtaigne", "noix"),
    "chicken": ("poulet", "viande"),
    "chickpea": ("pois chiche", "legume"),
    "chili pepper": ("piment", "epice"),
    "chinese cabbage": ("chou chinois", "legume"),
    "chive": ("ciboulette", "herbe"),
    "chocolate": ("chocolat", "autre"),
    "chorizo": ("chorizo", "viande"),
    "cinnamon": ("cannelle", "epice"),
    "clam": ("palourde", "poisson"),
    "clove": ("clou de girofle", "epice"),
    "cocoa": ("cacao", "autre"),
    "coconut": ("noix de coco", "fruit"),
    "cod": ("cabillaud", "poisson"),
    "coffee": ("café", "boisson"),
    "collard green": ("chou cavalier", "legume"),
    "coriander leaf": ("coriandre fraîche", "herbe"),
    "coriander seed": ("graine de coriandre", "epice"),
    "corn": ("maïs", "legume"),
    "cornmeal": ("semoule de maïs", "feculent"),
    "cottage cheese": ("cottage cheese", "fromage"),
    "couscous": ("couscous", "feculent"),
    "crab": ("crabe", "poisson"),
    "cranberry": ("canneberge", "fruit"),
    "cream cheese": ("fromage frais", "fromage"),
    "cucumber": ("concombre", "legume"),
    "cumin": ("cumin", "epice"),
    "currant": ("groseille", "fruit"),
    "curry powder": ("curry", "epice"),
    "date": ("datte", "fruit"),
    "dill": ("aneth", "herbe"),
    "egg white": ("blanc d'œuf", "autre"),
    "egg yolk": ("jaune d'œuf", "autre"),
    "eggplant": ("aubergine", "legume"),
    "endive": ("endive", "legume"),
    "fennel": ("fenouil", "legume"),
    "fennel seed": ("graine de fenouil", "epice"),
    "feta cheese": ("feta", "fromage"),
    "fig": ("figue", "fruit"),
    "garlic": ("ail", "legume"),
    "ginger": ("gingembre", "epice"),
    "goat cheese": ("fromage de chèvre", "fromage"),
    "gouda cheese": ("gouda", "fromage"),
    "grape": ("raisin", "fruit"),
    "great northern bean": ("haricot blanc", "legume"),
    "green bean": ("haricot vert", "legume"),
    "green bell pepper": ("poivron vert", "legume"),
    "green onion": ("oignon nouveau", "legume"),
    "green pea": ("petit pois", "legume"),
    "gruyere cheese": ("gruyère", "fromage"),
    "haddock": ("églefin", "poisson"),
    "ham": ("jambon", "viande"),
    "hazelnut": ("noisette", "noix"),
    "heavy cream": ("crème entière", "laitier"),
    "honey": ("miel", "condiment"),
    "honeydew melon": ("melon miel", "fruit"),
    "horseradish": ("raifort", "condiment"),
    "jack cheese": ("monterey jack", "fromage"),
    "jalapeno pepper": ("piment jalapeño", "epice"),
    "ketchup": ("ketchup", "condiment"),
    "kidney bean": ("haricot rouge", "legume"),
    "kiwi": ("kiwi", "fruit"),
    "lamb": ("agneau", "viande"),
    "lard": ("saindoux", "autre"),
    "leek": ("poireau", "legume"),
    "lemon": ("citron", "fruit"),
    "lemon peel": ("zeste de citron", "condiment"),
    "lentil": ("lentille", "legume"),
    "lettuce": ("laitue", "legume"),
    "lima bean": ("haricot de Lima", "legume"),
    "lime": ("citron vert", "fruit"),
    "mandarin orange": ("mandarine", "fruit"),
    "mango": ("mangue", "fruit"),
    "marjoram": ("marjolaine", "herbe"),
    "mint": ("menthe", "herbe"),
    "molasses": ("mélasse", "condiment"),
    "mozzarella cheese": ("mozzarella", "fromage"),
    "muenster cheese": ("munster", "fromage"),
    "mushroom": ("champignon", "legume"),
    "mussel": ("moule", "poisson"),
    "mustard": ("moutarde", "condiment"),
    "navy bean": ("haricot blanc sec", "legume"),
    "nectarine": ("nectarine", "fruit"),
    "neufchatel cheese": ("neufchâtel", "fromage"),
    "nutmeg": ("muscade", "epice"),
    "oat": ("avoine", "feculent"),
    "okra": ("gombo", "legume"),
    "olive": ("olive", "condiment"),
    "olive oil": ("huile d'olive", "condiment"),
    "onion": ("oignon", "legume"),
    "orange": ("orange", "fruit"),
    "orange peel": ("zeste d'orange", "condiment"),
    "orange roughy": ("hoplostète orange", "poisson"),
    "oregano": ("origan", "herbe"),
    "oyster": ("huître", "poisson"),
    "papaya": ("papaye", "fruit"),
    "paprika": ("paprika", "epice"),
    "parmesan cheese": ("parmesan", "fromage"),
    "parsley": ("persil", "herbe"),
    "parsnip": ("panais", "legume"),
    "pea": ("pois", "legume"),
    "peach": ("pêche", "fruit"),
    "peanut": ("cacahuète", "noix"),
    "peanut butter": ("beurre de cacahuète", "condiment"),
    "peanut oil": ("huile d'arachide", "condiment"),
    "pear": ("poire", "fruit"),
    "pecan": ("noix de pécan", "noix"),
    "persimmon": ("kaki", "fruit"),
    "pickle": ("cornichon", "condiment"),
    "pimento": ("piment doux", "legume"),
    "pine nut": ("pignon de pin", "noix"),
    "pineapple": ("ananas", "fruit"),
    "pinto bean": ("haricot pinto", "legume"),
    "pistachio": ("pistache", "noix"),
    "popcorn": ("pop-corn", "feculent"),
    "pork": ("porc", "viande"),
    "potato": ("pomme de terre", "legume"),
    "provolone cheese": ("provolone", "fromage"),
    "prune": ("pruneau", "fruit"),
    "pumpkin": ("potiron", "legume"),
    "pumpkin seed": ("graine de courge", "noix"),
    "quail": ("caille", "viande"),
    "rabbit": ("lapin", "viande"),
    "radish": ("radis", "legume"),
    "raisin": ("raisin sec", "fruit"),
    "raspberry": ("framboise", "fruit"),
    "red bean": ("haricot azuki", "legume"),
    "red bell pepper": ("poivron rouge", "legume"),
    "red cabbage": ("chou rouge", "legume"),
    "red onion": ("oignon rouge", "legume"),
    "red snapper": ("vivaneau", "poisson"),
    "red wine": ("vin rouge", "boisson"),
    "rhubarb": ("rhubarbe", "legume"),
    "rice": ("riz", "feculent"),
    "ricotta cheese": ("ricotta", "fromage"),
    "romano cheese": ("pecorino romano", "fromage"),
    "rosemary": ("romarin", "herbe"),
    "rum": ("rhum", "boisson"),
    "safflower oil": ("huile de carthame", "condiment"),
    "saffron": ("safran", "epice"),
    "sage": ("sauge", "herbe"),
    "sake": ("saké", "boisson"),
    "salami": ("salami", "viande"),
    "salmon": ("saumon", "poisson"),
    "sauerkraut": ("choucroute", "legume"),
    "sausage": ("saucisse", "viande"),
    "scallop": ("saint-jacques", "poisson"),
    "sesame oil": ("huile de sésame", "condiment"),
    "sesame seed": ("graine de sésame", "epice"),
    "shallot": ("échalote", "legume"),
    "sherry": ("xérès", "boisson"),
    "shrimp": ("crevette", "poisson"),
    "snow pea": ("pois gourmand", "legume"),
    "sorghum": ("sorgho", "feculent"),
    "sour cream": ("crème aigre", "laitier"),
    "spinach": ("épinard", "legume"),
    "strawberry": ("fraise", "fruit"),
    "sunflower seed": ("graine de tournesol", "noix"),
    "sweet potato": ("patate douce", "legume"),
    "swiss cheese": ("emmental", "fromage"),
    "tapioca": ("tapioca", "feculent"),
    "tarragon": ("estragon", "herbe"),
    "tea": ("thé", "boisson"),
    "thyme": ("thym", "herbe"),
    "tofu": ("tofu", "autre"),
    "tomato": ("tomate", "legume"),
    "tuna": ("thon", "poisson"),
    "turkey": ("dinde", "viande"),
    "turmeric": ("curcuma", "epice"),
    "turnip": ("navet", "legume"),
    "vanilla": ("vanille", "epice"),
    "veal": ("veau", "viande"),
    "venison": ("gibier (cerf)", "viande"),
    "vinegar": ("vinaigre", "condiment"),
    "vodka": ("vodka", "boisson"),
    "walnut": ("noix", "noix"),
    "water chestnut": ("châtaigne d'eau", "legume"),
    "watercress": ("cresson", "legume"),
    "watermelon": ("pastèque", "fruit"),
    "white pepper": ("poivre blanc", "epice"),
    "white wine": ("vin blanc", "boisson"),
    "wild rice": ("riz sauvage", "feculent"),
    "yam": ("igname", "legume"),
    "yellow bell pepper": ("poivron jaune", "legume"),
    "yogurt": ("yaourt", "laitier"),
    "zucchini": ("courgette", "legume"),
}

CATEGORY_LABELS = {
    "fruit": ("Fruits", "🍓"),
    "legume": ("Légumes", "🥬"),
    "herbe": ("Herbes", "🌿"),
    "epice": ("Épices", "🌶️"),
    "viande": ("Viandes", "🥩"),
    "poisson": ("Mer & poissons", "🦐"),
    "fromage": ("Fromages", "🧀"),
    "laitier": ("Laitages", "🥛"),
    "feculent": ("Céréales & féculents", "🌾"),
    "noix": ("Noix & graines", "🥜"),
    "condiment": ("Condiments", "🫙"),
    "boisson": ("Boissons", "🍷"),
    "autre": ("Autres", "🍫"),
}

# FooDB flavor descriptor translations (top descriptors by usage)
FLAVOR_FR = {
    "sweet": "sucré", "fruity": "fruité", "green": "vert", "bitter": "amer",
    "floral": "floral", "woody": "boisé", "herbal": "herbacé", "spicy": "épicé",
    "citrus": "agrume", "fresh": "frais", "fatty": "gras", "waxy": "cireux",
    "earthy": "terreux", "nutty": "noisette", "sulfurous": "soufré",
    "balsamic": "balsamique", "roasted": "grillé", "caramellic": "caramel",
    "caramel": "caramel", "creamy": "crémeux", "buttery": "beurré",
    "cheesy": "fromager", "cheese": "fromager", "sour": "acide", "pungent": "piquant",
    "vanilla": "vanillé", "smoky": "fumé", "minty": "mentholé",
    "camphoreous": "camphré", "medicinal": "médicinal", "phenolic": "phénolique",
    "musty": "de cave", "mushroom": "champignon", "meaty": "carné",
    "oily": "huileux", "winey": "vineux", "fermented": "fermenté",
    "alliaceous": "alliacé", "onion": "oignon", "garlic": "ail",
    "berry": "fruits rouges", "apple": "pomme", "banana": "banane",
    "pineapple": "ananas", "pear": "poire", "peach": "pêche",
    "cherry": "cerise", "grape": "raisin", "melon": "melon",
    "coconut": "coco", "almond": "amande", "honey": "miel",
    "rose": "rose", "jasmine": "jasmin", "lavender": "lavande",
    "lemon": "citron", "orange": "orange", "lime": "citron vert",
    "grapefruit": "pamplemousse", "tropical": "tropical", "anise": "anisé",
    "licorice": "réglisse", "clove": "girofle", "cinnamon": "cannelle",
    "pepper": "poivré", "peppery": "poivré", "gasoline": "essence",
    "ethereal": "éthéré", "alcoholic": "alcoolisé", "whiskey": "whisky",
    "rummy": "rhum", "chocolate": "chocolat", "coffee": "café",
    "burnt": "brûlé", "toasted": "toasté", "bready": "pain",
    "yeasty": "levure", "malty": "malté", "grain": "céréale",
    "hay": "foin", "grassy": "herbe coupée", "leafy": "feuille",
    "vegetable": "végétal", "tomato": "tomate", "potato": "pomme de terre",
    "cucumber": "concombre", "cabbage": "chou", "radish": "radis",
    "horseradish": "raifort", "mustard": "moutarde", "fishy": "marin",
    "amine": "aminé", "animal": "animal", "leathery": "cuir",
    "tobacco": "tabac", "tea": "thé", "mint": "menthe",
    "eucalyptus": "eucalyptus", "pine": "pin", "resinous": "résineux",
    "terpenic": "terpénique", "turpentine": "térébenthine",
    "soapy": "savonneux", "metallic": "métallique", "plastic": "plastique",
    "rubbery": "caoutchouc", "sharp": "vif", "mild": "doux",
    "bland": "neutre", "odorless": "inodore", "sweaty": "sueur",
    "rancid": "rance", "sulfur": "soufre", "eggy": "œuf",
    "dairy": "lacté", "milky": "lacté", "buttermilk": "babeurre",
    "yogurt": "yaourt", "estery": "estérifié", "candy": "bonbon",
    "bubble gum": "chewing-gum", "jammy": "confituré", "cooked": "cuit",
    "baked": "cuit au four", "fried": "frit", "tallow": "suif",
    "lard": "saindoux", "brothy": "bouillon", "savory": "umami",
    "umami": "umami", "salty": "salé", "astringent": "astringent",
    "cooling": "rafraîchissant", "warming": "réchauffant",
    "aromatic": "aromatique", "fragrant": "parfumé", "heavy": "lourd",
    "light": "léger", "powdery": "poudré", "musk": "musqué",
    "ambery": "ambré", "incense": "encens", "spice": "épice",
    "wintergreen": "gaulthérie", "menthol": "menthol", "cocoa": "cacao",
    "walnut": "noix", "hazelnut": "noisette", "peanut": "cacahuète",
    "sesame": "sésame", "popcorn": "pop-corn", "corn": "maïs",
    "rice": "riz", "coumarin": "coumarine", "naphthalic": "naphtalique",
    "acidic": "acidulé", "acetic": "vinaigré", "vinegar": "vinaigre",
    "cognac": "cognac", "brandy": "brandy", "wine": "vin",
    "beer": "bière", "solvent": "solvant", "acrid": "âcre",
    "smoke": "fumée", "ashy": "cendré", "charred": "carbonisé",
    "terpene": "terpénique", "camphor": "camphré", "citrusy": "agrume",
    "herbaceous": "herbacé", "woodsy": "boisé", "earthly": "terreux",
    "fruit": "fruité", "flower": "floral", "sweetish": "sucré",
    "buttery-like": "beurré", "creme": "crème", "custard": "crème anglaise",
    "marshmallow": "guimauve", "maple": "érable", "molasses": "mélasse",
    "raisin": "raisin sec", "plum": "prune", "apricot": "abricot",
    "strawberry": "fraise", "raspberry": "framboise", "blueberry": "myrtille",
    "blackcurrant": "cassis", "currant": "groseille", "fig": "figue",
    "date": "datte", "mango": "mangue", "papaya": "papaye",
    "passionfruit": "fruit de la passion", "guava": "goyave", "quince": "coing",
    "citron": "cédrat", "bergamot": "bergamote", "mandarin": "mandarine",
    "tangerine": "mandarine", "kiwi": "kiwi", "watermelon": "pastèque",
    "cantaloupe": "cantaloup", "honeydew": "melon miel", "celery": "céleri",
    "carrot": "carotte", "pea": "petit pois", "bean": "haricot",
    "asparagus": "asperge", "artichoke": "artichaut", "beet": "betterave",
    "spinach": "épinard", "lettuce": "laitue", "broccoli": "brocoli",
    "cauliflower": "chou-fleur", "turnip": "navet", "parsnip": "panais",
    "pumpkin": "potiron", "squash": "courge", "zucchini": "courgette",
    "eggplant": "aubergine", "pepper bell": "poivron", "chili": "piment",
    "leek": "poireau", "shallot": "échalote", "chive": "ciboulette",
    "scallion": "oignon nouveau", "parsley": "persil", "dill": "aneth",
    "basil": "basilic", "thyme": "thym", "oregano": "origan",
    "rosemary": "romarin", "sage": "sauge", "tarragon": "estragon",
    "marjoram": "marjolaine", "fennel": "fenouil", "caraway": "carvi",
    "cumin": "cumin", "coriander": "coriandre", "cardamom": "cardamome",
    "ginger": "gingembre", "saffron": "safran", "nutmeg": "muscade",
    "allspice": "piment de la Jamaïque", "juniper": "genièvre",
    "bay": "laurier", "verbena": "verveine", "chamomile": "camomille",
    "geranium": "géranium", "violet": "violette", "lilac": "lilas",
    "hyacinth": "jacinthe", "honeysuckle": "chèvrefeuille", "orris": "iris",
    "narcissus": "narcisse", "gardenia": "gardénia", "magnolia": "magnolia",
    "orange blossom": "fleur d'oranger", "neroli": "néroli",
    "petitgrain": "petitgrain", "citronella": "citronnelle",
    "lemongrass": "citronnelle",     "spearmint": "menthe verte",
    "watercress": "cresson", "horseradish-like": "raifort",
    "yeast": "levure", "bay oil": "laurier", "bread": "pain",
    "metal": "métallique", "fat": "gras", "ammoniacal": "ammoniaqué",
    "cultured dairy": "lacté fermenté", "resin": "résineux",
    "storax": "styrax", "aldehydic": "aldéhydé", "wood": "boisé",
    "medical": "médicinal", "ammonia": "ammoniaque",
    "orange peel": "zeste d'orange", "peely": "zesté",
    "unripe banana": "banane verte", "grass": "herbe coupée",
    "fusel": "fusel", "oil": "huileux", "curry": "curry",
    "warm": "chaud", "must": "moût", "green tea": "thé vert",
    "seaweed": "algue", "shellfish": "crustacé", "crab": "crabe",
    "fish": "poisson", "mold": "moisi", "mousy": "souris",
    "naphthyl": "naphtalique", "petroleum": "pétrole",
    "sulfurous onion": "oignon soufré", "roasted meat": "viande rôtie",
    "roasted nut": "noix grillée", "smoked": "fumé",
    "sweet corn": "maïs doux", "tomato leaf": "feuille de tomate",
    "tropical fruit": "fruit tropical", "vanillin": "vanilline",
    "clean": "net", "dry": "sec", "dusty": "poussiéreux",
    "ripe fruit": "fruit mûr", "overripe fruit": "fruit trop mûr",
    "fresh air": "air frais", "ozone": "ozone",
}
